# å½“å‰ç‰ˆæœ¬ | Theme Version
Hexo: "2.1"

#è¯­è¨€ | Language
# en | zh-Hans
#è¯·åœ¨hexoæ–‡ä»¶ä¸‹çš„"_config.yml"ä¿®æ”¹language
language: en

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: 'ğŸ™ğŸ¾'

# åˆå§‹åŒ–é£æ ¼ | Default Style "black/light"
# style: black
style: light

#SEOä¼˜åŒ–

## ç½‘ç«™æè¿°
description: æ¬¢è¿ğŸ‘ğŸ»

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: notebook

# é¦–é¡µURL | Your URL
link: Your_URL

# ä½ çš„æ˜µç§° | Your Name
author: Your Name

#hexo links
hexo_links: https://hexo.io

# ç«™ç‚¹å°å›¾æ ‡åœ°å€ | Small Icon of Your Site
favicon: /img/favicon.ico

# èœå•æ é…ç½® | Nav Bar Settings
menu:
  2012è‡³ä»Š: /
  Markdown: /Markdown

  


# ç«™å†…å…³é”®è¯æœç´¢ | Local Search
search:
 enable: true
 path: search.xml
 field: post
 # onload: true

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalse
valine:
  enable: true
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz

# visitors count
counter:
  enable: true


highlight:
  enable: true
